### ISSUE TITLE
Attach anchor IDs to <li> instead of parent <ol>

### ISSUE THREAD

**Issue by jenschlot** [grant-g/marked-it#3]
Following this coding:
<img width="463" alt="screen shot 2017-08-18 at 3 50 34 pm" src="https://user-images.githubusercontent.com/11622088/29477200-025255c0-842d-11e7-972a-e0171b2fee22.png">

The anchor should be applied to the `li` output, instead of the parent `ol`. Current implementation applies it to the top of the list:
![pasted image at 2017_08_18 03_37 pm](https://user-images.githubusercontent.com/11622088/29476991-014dd880-842c-11e7-8e55-73e8d921be44.png)

**Comment by grant-g** [comment]
I forgot that the syntax for this to put the attribute at the front, like:

3. {: hi} content...

So no changes needed, closing.
